#!/bin/bash
# Taken from:
#    https://raw.github.com/kaihendry/Kai-s- … r/.xinitrc
#
# for terminus font in Archlinux sad

while true
do
    VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
    LOCALDATE=$(date +%d.%m.%Y)
    LOCALTIME=$(date +%H:%M)
    IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1) # can get confused if you use vmware
    TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"

    xsetroot -name "V=$VOL | $LOCALTIME | $LOCALDATE"
    sleep 20s
done &

exec feh --bg-scale /home/petrovj12/Pictures/night.jpeg &
exec xcompmgr &

exec dwm
